// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: dotenv.env['FIREBASE_APP_ID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN']!,
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvwTr3aswCSMhFC2-eLjQ6VA2xRHNfonk',
    appId: '1:406762670130:android:c863294c9976782a34142b',
    messagingSenderId: '406762670130',
    projectId: 'post-notifs',
    storageBucket: 'post-notifs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZQQHka7FsbK_oSwcKTuspzOZ64kYzPQ',
    appId: '1:406762670130:ios:39847047a1caf6d234142b',
    messagingSenderId: '406762670130',
    projectId: 'post-notifs',
    storageBucket: 'post-notifs.appspot.com',
    iosClientId: '406762670130-tf66249h4n1dc7gn7kevaqodq4ri0n86.apps.googleusercontent.com',
    iosBundleId: 'com.example.postNotifs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZQQHka7FsbK_oSwcKTuspzOZ64kYzPQ',
    appId: '1:406762670130:ios:39847047a1caf6d234142b',
    messagingSenderId: '406762670130',
    projectId: 'post-notifs',
    storageBucket: 'post-notifs.appspot.com',
    iosClientId: '406762670130-tf66249h4n1dc7gn7kevaqodq4ri0n86.apps.googleusercontent.com',
    iosBundleId: 'com.example.postNotifs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYj5jJ2NgkFIqGsKh7o-PO2HiB_h6EDDQ',
    appId: '1:406762670130:web:9c6414bd1a62443734142b',
    messagingSenderId: '406762670130',
    projectId: 'post-notifs',
    authDomain: 'post-notifs.firebaseapp.com',
    storageBucket: 'post-notifs.appspot.com',
  );
}
